#!/bin/bash

COOKIE=`mktemp`
NIC="OVH-NICHANDLE"
PASS="THESUPERSECRETPASSWORD"
DOMAINS="DOMAIN1 DOMAIN2"

source .config

# Login 
curl -k -c $COOKIE --compressed -i -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' -H 'Host: www.ovh.com' -X POST -d "session_nic=${NIC}&session_password=${PASS}&language=en&Connexion=Connexion" https://www.ovh.com/managerv3/login.pl  >/dev/null 2>&1


for DOMAIN in $DOMAINS; do 
    echo -n "$DOMAIN: "
    NUM=1
    FormData=""
    for type in READY ACTIVE; do 
    	while read KEY; do 
	    
	    if [ "${NUM}" -gt 5 ]; then 
		break  # No more than 5 for OVH
 	    fi
	    KeyFlag=$(perl -MURI::Escape -e 'print uri_escape($ARGV[0]);' "`echo $KEY|cut -d ' ' -f 5`")
	    KeyAlgo=$(perl -MURI::Escape -e 'print uri_escape($ARGV[0]);' "`echo $KEY|cut -d ' ' -f 7`")
	    KeyPubk=$(perl -MURI::Escape -e 'print uri_escape($ARGV[0]);' "`echo $KEY|cut -d ' ' -f 8`")
	    KeyTag=$(perl -MURI::Escape -e 'print uri_escape($ARGV[0]);' "`echo $KEY|cut -d ' ' -f 10`")

	    FormData="${FormData}keyTag_${NUM}=${KeyTag}&flag_${NUM}=${KeyFlag}&algoId_${NUM}=${KeyAlgo}&pubKey_${NUM}=${KeyPubk}&"
	    NUM=$((NUM+1))
	    echo -n "."
        done <<< "`ods-ksmutil key export --zone $DOMAIN --keytype KSK --keystate $type |grep $DOMAIN|sed -re 's/(\t|;|=)+/ /g;s/ +/ /g'`";
    done;
    
    FormData="${FormData}language=en&domain=${DOMAIN}&hostname=${DOMAIN}&service=${DOMAIN}&lastxsldoc=hosting%2Fdomain%2Fhosting-domain-registry-ds-modify.xsl&csid=0&todo=DomainDsUpdate&xsldoc=hosting%2Fdomain%2Fhosting-domain-registry-ds.xsl"
    
    # Save the DNSKEY
    curl -k -b $COOKIE --compressed -i 'https://www.ovh.com/managerv3/hosting-domain-registry-ds.pl' -H 'Host: www.ovh.com' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' -H 'Content-Type: application/x-www-form-urlencoded' --data "${FormData}" >/dev/null 2>&
    echo " DONE."
done;

rm -f "$COOKIE"
