#!/bin/bash

# This script receives from STDIN the new KSK for the rollover in the following form : 
# <zone> <ttl> <class> <type> DNSKEY <flags> <protocol> <algorithm> <public key>

IN=`cat |sed -re 's/\t+/ /g;s/ +/ /g'`

COOKIE=`mktemp`
NIC="OVH-NICHANDLE"
PASS="THESUPERSECRETPASSWORD"

POVH=/PATH/TO/SCRIPT

source $POVH/.config


if [[ -n "$CONF" ]]; then
    EXTRA_ARGS="--config $CONF"
fi;

# Login 
curl -k -c $COOKIE --compressed -i -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' -H 'Host: www.ovh.com' -X POST -d "session_nic=${NIC}&session_password=${PASS}&language=en&Connexion=Connexion" https://www.ovh.com/managerv3/login.pl  >/dev/null 2>&1


DOMAIN=`echo -n $IN |cut -d ' ' -f 1|sed -re 's/\.$//'`

    # get DNSSEC Key already registred
KEYLIST=`curl -k -b $COOKIE --compressed -i  "https://www.ovh.com/managerv3/hosting-domain-registry-ds.pl?xsldoc=hosting%2Fdomain%2Fhosting-domain-registry-ds-modify.xsl&language=fr&domain=${DOMAIN}&hostname=${DOMAIN}&service=${DOMAIN}&lastxsldoc=hosting%2Fdomain%2Fhosting-domain-registry-ds.xsl&csid=0&typeFreeHosting=" -H 'Host: www.ovh.com'  -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' 2>/dev/null |tr -d '\n'`

MKeyFlag=`echo -n $IN |cut -d ' ' -f 5`
MKeyAlgo=`echo -n $IN |cut -d ' ' -f 7`
MKeyPubk=`echo -n $IN |cut -d ' ' -f "8-"`

if echo "$KEYLIST" |grep -qi "${MKeyPubk}"; then
    # Already in OVH
    exit 2
fi


# We could calculate it from all parameters : see http://www.v13.gr/blog/?p=239
MKeyTag=`ods-ksmutil $EXTRA_ARGS key export --zone $DOMAIN --keytype KSK |grep "${MKeyPubk}"|sed -re 's/(\t|;|=)+/ /g;s/ +/ /g'|cut -d ' ' -f 10`


DONE="0"

for NUM in `seq 1 6`; do
    if [ "${NUM}" -gt 5 ]; then
	if [[ $DONE == "0" ]]; then
	    exit 1;
	else
	    break
	fi
    fi;

    # Check if $NUM offset is empty or if the $NUM offset have an not (active|publish|generate|ready) key (dead/retire or missing)
    KeyTagOVH=`echo $KEYLIST|sed -re 's/</\n/g;s/>/\n/g'|grep "inputKeyTag${NUM}"|sed -re 's/.*value="([0-9]*)".*/\1/'`
    KeyTagInODS=`ods-ksmutil $EXTRA_ARGS key list --verbose 2>/dev/null|grep " KSK "|grep " $KeyTagOVH"`
    if ( [[ $DONE == "0" ]] ) && (([[ "x${KeyTagOVH}" == "x" ]]) || (! echo -ne "${KeyTagInODS}"|grep -qEi "(active|publish|generate|ready)")); then
	# Empty offset or Non empty but not needed key
	KeyFlag=$(perl -MURI::Escape -e 'print uri_escape($ARGV[0]);' "$MKeyFlag")
	KeyAlgo=$(perl -MURI::Escape -e 'print uri_escape($ARGV[0]);' "$MKeyAlgo")
	KeyPubk=$(perl -MURI::Escape -e 'print uri_escape($ARGV[0]);' "$MKeyPubk")
	KeyTag=$(perl -MURI::Escape -e 'print uri_escape($ARGV[0]);' "$MKeyTag")
        DONE="1"
    elif [[ $DONE == "1" ]] && (! [[ "x${KeyTagOVH}" == "x" ]]) && (echo -ne "${KeyTagInODS}"|grep -qEi "(active|publish|generate|ready)") ; then
	#Not empty and needed
	# We save it

	# Algo
	KA=`echo $KEYLIST|sed -re 's/</\n/g;s/>/\n/g'|grep -E "(id=\"selectAlgo${NUM}\"|option value=.* selected)"|grep "id=\"selectAlgo${NUM}\"" -A 1|grep "value=" |sed -re 's/.*value="([0-9]*)".*/\1/'`
	# Flag
	KF=`echo $KEYLIST|sed -re 's/</\n/g;s/>/\n/g'|grep -E "(id=\"selectFlag${NUM}\"|option value=.* selected)"|grep "id=\"selectFlag${NUM}\"" -A 1|grep "value=" |sed -re 's/.*value="([0-9]*)".*/\1/'`
	#PubKey
	KP=`echo $KEYLIST|sed -re 's/</\n/g;s/>/\n/g'|grep "inputPubKey${NUM}" -A 1|grep -v textarea`
	#KeyTag
	
	KeyFlag=$(perl -MURI::Escape -e 'print uri_escape($ARGV[0]);' "$KF")
	KeyAlgo=$(perl -MURI::Escape -e 'print uri_escape($ARGV[0]);' "$KA")
	KeyPubk=$(perl -MURI::Escape -e 'print uri_escape($ARGV[0]);' "$KP")
	KeyTag=$(perl -MURI::Escape -e 'print uri_escape($ARGV[0]);' "$KeyTagOVH")
    else
	#empty form
	KeyFlag=""
	KeyAlgo=""
	KeyPubk=""
	KeyTag=""

    fi;
    FormData="${FormData}keyTag_${NUM}=${KeyTag}&flag_${NUM}=${KeyFlag}&algoId_${NUM}=${KeyAlgo}&pubKey_${NUM}=${KeyPubk}&"
done;


FormData="${FormData}language=en&domain=${DOMAIN}&hostname=${DOMAIN}&service=${DOMAIN}&lastxsldoc=hosting%2Fdomain%2Fhosting-domain-registry-ds-modify.xsl&csid=0&todo=DomainDsUpdate&xsldoc=hosting%2Fdomain%2Fhosting-domain-registry-ds.xsl"


# Save the DNSKEY
curl -k -b $COOKIE --compressed -i 'https://www.ovh.com/managerv3/hosting-domain-registry-ds.pl' -H 'Host: www.ovh.com' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' -H 'Content-Type: application/x-www-form-urlencoded' --data "${FormData}" >/dev/null 2>&1


#LOGOUT
curl -k -b $COOKIE --compressed -i 'https://www.ovh.com/managerv3/logout.pl?language=fr&hostname=&lastxsldoc=sub-home.xsl&csid=0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' -H 'Accept-Encoding: gzip, deflate' -H 'Host: www.ovh.com' 2>/dev/null >/dev/null

rm -f "$COOKIE"

